"""Common constants and configuration keys for the streaming package."""

from __future__ import annotations

# Kafka Topics
TOPIC_MATCH_EVENTS = "match-events"
TOPIC_PLAYER_EVENTS = "player-events"
TOPIC_TEAM_EVENTS = "team-events"
TOPIC_ANALYTICS_EVENTS = "analytics-events"
TOPIC_PIPELINE_EVENTS = "pipeline-events"
TOPIC_SYSTEM_EVENTS = "system-events"

ALL_TOPICS = (
    TOPIC_MATCH_EVENTS,
    TOPIC_PLAYER_EVENTS,
    TOPIC_TEAM_EVENTS,
    TOPIC_ANALYTICS_EVENTS,
    TOPIC_PIPELINE_EVENTS,
    TOPIC_SYSTEM_EVENTS,
)

# Defaults
DEFAULT_BOOTSTRAP_SERVERS = ["localhost:9092"]
DEFAULT_CLIENT_ID = "sporta-streaming-client"
DEFAULT_GROUP_ID = "sporta-analytics-group"

# Event Types
EVENT_TYPE_PASS = "PASS"
EVENT_TYPE_SHOT = "SHOT"
EVENT_TYPE_FOUL = "FOUL"
EVENT_TYPE_CARD = "CARD"
EVENT_TYPE_SUBSTITUTION = "SUBSTITUTION"
EVENT_TYPE_TACKLE = "TACKLE"
EVENT_TYPE_INTERCEPTION = "INTERCEPTION"
EVENT_TYPE_SAVE = "SAVE"
EVENT_TYPE_GOAL = "GOAL"
EVENT_TYPE_SYSTEM = "SYSTEM"

VALID_EVENT_TYPES = (
    EVENT_TYPE_PASS,
    EVENT_TYPE_SHOT,
    EVENT_TYPE_FOUL,
    EVENT_TYPE_CARD,
    EVENT_TYPE_SUBSTITUTION,
    EVENT_TYPE_TACKLE,
    EVENT_TYPE_INTERCEPTION,
    EVENT_TYPE_SAVE,
    EVENT_TYPE_GOAL,
    EVENT_TYPE_SYSTEM,
)
